base_url = "https://jds.work"
title = "JDs Work"
description = "A blog about technology, careers, and personal growth."
compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
github_url = "https://github.com/juliusdelta"
mastodon_url = "https://fosstodon.org/@Juliusdelta"

[extra.expressions]
pinned = "Written On"
