# The URL the site will be built for
base_url = "https://jds.work"
title = "JDs Work"
description = "A blog about tech, career, and growing."
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

theme = "zerm"

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "JD"
show_author = false
show_categories = true
show_tags = true
theme_color = "blue"
center = true
show_menu_items = 2
logo_text = "JDs Work"
logo_home_link = "/"
main_menu = [
    {url="/about/", name="about"}
]
menu_more = "show more"
read_more = "read more"

# not currently used from previous theme, but leaving here for now in case I
# feel like adding it.
#read_other_posts = "read other posts"
# after_dark_menu = [
#     {url = "$BASE_URL", name = "Home"},
#     {url = "$BASE_URL/categories", name = "Categories"},
#     {url = "$BASE_URL/tags", name = "Tags"},
#     {url = "https://github.com/juliusdelta", name = "Github"},
# ]
# after_dark_title = "JDs Work"
