base_url = "https://jds.work"
title = "JDs Work"
description = "A blog about technology, careers, and personal growth."
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "nord"

[extra]
logo_text = "JDs Work"
logo_home_link = "/"
menu_links = [
  { url = "$BASE_URL/", name = "Blog" },
  { url = "$BASE_URL/uses/", name = "Uses" },
  { url = "$BASE_URL/about/", name = "About" },
]
github_url = "https://github.com/juliusdelta"
mastodon_url = "https://fosstodon.org/@Juliusdelta"
